// <auto-generated />
using Empresa.CategoriasApi.Infra.Data.ORM.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empresa.CategoriasApi.Infra.Data.Migrations
{
    [DbContext(typeof(CategoriaDbContext))]
    partial class CategoriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Empresa.CategoriasApi.Domains.Entities.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("categoria_id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("categoria")
                        .HasColumnType("VarChar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
